name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
    - run: flutter pub get
    - run: flutter build ipa --release
    - uses: actions/upload-artifact@v4
      with:
        name: release-ipa
        path: build/ios/ipa/*.ipa
